Add more clients
aserto-dev/aserto-go pull request #26
Opened 2022-02-16 15:55 UTC by florindragos

2022-02-21 17:18 UTC, ronenh commented on client/options.go
> +		options.DialOptions = append(options.DialOptions, grpc.WithUnaryInterceptor(mw))
We already set a unary and stream interceptor on the connection to inject the tenant ID (https://github.com/aserto-dev/aserto-go/blob/main/client/connection.go#L99-L100) and this will overwrite our interceptors.

I think we should use `grpc.WithChainUnaryInterceptor` internally to make sure that both the user's interceptor and ours are applied.

In addition, if we're letting users add interceptors, we should also expose a `WithChainUnaryInterceptor` and `WithChainStreamInterceptr` options to add multiple interceptors.

2022-02-22 19:20 UTC, ronenh commented on client/options.go
> +func WithChainUnaryInterceptor(mw grpc.UnaryClientInterceptor) ConnectionOption {
It would be good to remain consistent with [grpc.WithChainUnaryInterceptor](https://pkg.go.dev/google.golang.org/grpc#WithChainUnaryInterceptor) and have the function take a parameter of type `...grpc.UnaryClientInterceptor`.
This way users can pass in all of their middleware in a single call if they wish, just like they do when dialing their own grpc connections.

2022-02-22 19:20 UTC, ronenh commented on client/connection.go
> +	for _, mw := range options.StreamClientInterceptors {
I don't think you need to loop over `options.StreamClientInterceptors` and add them one by one. You should be able to call `grpc.WithChainStreamInterceptor(options.UnaryClientInterceptors...)` and create a single dial option with all the chained interceptors.

2022-02-24 10:51 UTC, florindragos commented on client/connection.go
> +	for _, mw := range options.StreamClientInterceptors {
yes, good idea

2022-02-24 15:42 UTC, ronenh requested changes

2022-02-24 15:42 UTC, ronenh commented on client/connection_test.go
> +func TestWithBearerTokenAuth(t *testing.T) {
🏆

2022-02-24 15:42 UTC, ronenh commented on client/options.go
> +func WithChainUnaryInterceptor(mw grpc.UnaryClientInterceptor) ConnectionOption {
The signature should be `func WithChainUnaryInterceptor(mw ...grpc.UnaryClientInterceptor) ConnectionOption` to allow users to pass multiple interceptors. Just like the standard `grpc.WithChainUnaryInterceptor`.

2022-02-24 15:42 UTC, ronenh commented on client/registry/registry.go
> +package authorizer
`package registry` and `registry_tenant` below.

2022-02-24 17:19 UTC, ronenh approved these changes

2022-02-24 17:53 UTC, merged