Use authorizer v2
aserto-dev/aserto-go pull request #42
Opened 2022-10-05 09:45 UTC by oanatmaria

2022-10-05 21:19 UTC, ronenh approved these changes
Looks great. You probably want to make a corresponding change in [aserto-docs](https://github.com/aserto-dev/aserto-docs/tree/main/docs/software-development-kits/go)

2022-10-06 13:49 UTC, carabasdaniel commented on README.md
> +		Name:      "peoplefinder",
The name is not needed, either replace the id by the pair of name and label (instance label) or just don't add it

2022-10-06 13:54 UTC, carabasdaniel requested changes
The changes do not replace the policy.id with policy name in v2

2022-10-06 13:54 UTC, carabasdaniel commented on examples/middleware/http/gorilla/main.go
> +			Name:     "local",
see previous comments

2022-10-06 13:54 UTC, carabasdaniel commented on middleware/grpc/internal/pbutil/select_test.go
> +			Name: "policyName",
see previous comments

2022-10-06 13:54 UTC, carabasdaniel commented on middleware/grpc/internal/pbutil/select_test.go
> +				"name": "policyName",
see previous comments

2022-10-06 13:54 UTC, carabasdaniel commented on middleware/http/std/example_test.go
> +			Name:     "<Aserto policy Name>",
see previous comments

2022-10-06 13:54 UTC, carabasdaniel commented on middleware/policy.go
> +	Name string
should contain the instance label also

2022-10-11 09:09 UTC, carabasdaniel commented on README.md
> +		Name: "<Policy Name>",
Do you not need the instance label in the middleware.Policy declaration ?

2022-10-11 11:12 UTC, carabasdaniel approved these changes

2022-10-11 11:45 UTC, merged